spring.application.name=biblioteca
spring.datasource.url=jdbc:h2:mem:biblioteca
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

springdoc.openapi.servers[0].url=https://obscure-train-wj6wp5767pr2gxp4-8080.app.github.dev
springdoc.openapi.servers[0].description=Ambiente Codespaces