# Configurações do Projeto e Banco de Dados H2
spring.application.name=biblioteca
spring.datasource.url=jdbc:h2:mem:biblioteca
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Geração automática de tabelas e Console H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logs do Banco de Dados no Terminal (Excelente para fins didáticos)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuração do Swagger para o Ambiente GitHub Codespaces
springdoc.openapi.servers[0].url=https://obscure-train-wj6wp5767pr2gxp4-8080.app.github.dev
springdoc.openapi.servers[0].description=Ambiente Codespaces
